### ISSUE TITLE
font issues in localisation selector

### ISSUE THREAD

**Issue by jonorthwash** [common-voice/common-voice#3099]
I'm seeing some font issues in the localisation dropdown.  Specifically the following two:

The character "Ə" in Azərbaycanca:
![Screenshot from 2021-04-21 19-31-34](https://user-images.githubusercontent.com/963849/115634828-610fe780-a2d8-11eb-88d3-523827401404.png)

And the "Ԥ" in Аԥсуа:
![Screenshot from 2021-04-21 19-30-53](https://user-images.githubusercontent.com/963849/115634829-610fe780-a2d8-11eb-8f90-c1170d910e50.png)

I'm using Mozilla Firefox 78.9.0esr on Debian sid.

**Comment by jonorthwash** [comment]
The issues with "ə" pop up in other places:
![Screenshot from 2021-04-21 19-35-34](https://user-images.githubusercontent.com/963849/115635046-cb288c80-a2d8-11eb-9702-46f6f83340eb.png)
![Screenshot from 2021-04-21 19-36-50](https://user-images.githubusercontent.com/963849/115635113-f14e2c80-a2d8-11eb-987e-5796fa825e42.png)
![Screenshot from 2021-04-21 19-36-34](https://user-images.githubusercontent.com/963849/115635115-f14e2c80-a2d8-11eb-8dfc-6b66cc815c8e.png)

**Comment by phirework** [comment]
I've pushed a fix to dev, can you verify? https://dev.commonvoice.allizom.org/en

**Comment by jonorthwash** [comment]
Аԥсуа is still a problem.  The other parts I can see on the dev server seem better.

**Comment by phirework** [comment]
That might be an issue with the underlying font family, which I'm going to redirect to the ongoing thread in #1141. The above fix is now on production. Thanks!
